name: TagBot
on:
  schedule:
    - cron: 0 * * * *
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
        uses: JuliaRegistries/TagBot@v1.5.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}